name: Cypress E2E Tests
run-name: End-to-end for ${{ github.repository }}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  cypress-celina1:
    name: Celina 1
    runs-on: ubuntu-24.04
    steps:
      - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout Backend repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: RAF-SI-2025/EXBanka-4-Backend
          path: EXBanka-4-Backend

      - name: Checkout Infrastructure repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: RAF-SI-2025/EXBanka-4-Infrastructure
          path: infrastructure

      - name: Create .env from secrets
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo $SECRETS_CONTEXT | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" >> infrastructure/.env

      - name: Start backend
        run: docker compose up -d
        working-directory: ${{ github.workspace }}/infrastructure

      - name: Wait for services to start up and check health
        run: |
          while docker compose ps | grep "starting"
          do
            sleep 5
          done
          if docker compose ps | grep "unhealthy"
          then
            echo "One or more backend services are unhealthy. Check the logs for details."
            exit 1
          fi
        working-directory: ${{ github.workspace }}/infrastructure

      - name: Copy frontend environment variables
        run: cp .github/workflows/cypress.env.test.json cypress.env.json

      - name: Run Cypress - celina1
        timeout-minutes: 30
        uses: cypress-io/github-action@783cb3f07983868532cabaedaa1e6c00ff4786a8
        with:
          start: npm run preview
          wait-on: http://localhost:4173/
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/celina1/**
        env:
          VITE_API_URL: http://localhost:8083

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-celina1
          path: cypress/screenshots

  cypress-celina2:
    name: Celina 2
    runs-on: ubuntu-24.04
    steps:
      - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Backend repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: RAF-SI-2025/EXBanka-4-Backend
          path: EXBanka-4-Backend

      - name: Checkout Infrastructure repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: RAF-SI-2025/EXBanka-4-Infrastructure
          path: infrastructure

      - name: Create .env from secrets
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo $SECRETS_CONTEXT | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" >> infrastructure/.env

      - name: Start backend
        run: docker compose up -d
        working-directory: ${{ github.workspace }}/infrastructure

      - name: Wait for services to start up and check health
        run: |
          while docker compose ps | grep "starting"
          do
            sleep 5
          done
          if docker compose ps | grep "unhealthy"
          then
            echo "One or more backend services are unhealthy. Check the logs for details."
            exit 1
          fi
        working-directory: ${{ github.workspace }}/infrastructure

      - name: Copy frontend environment variables
        run: cp .github/workflows/cypress.env.test.json cypress.env.json

      - name: Run Cypress - celina2
        timeout-minutes: 30
        uses: cypress-io/github-action@783cb3f07983868532cabaedaa1e6c00ff4786a8
        with:
          start: npm run preview
          wait-on: http://localhost:4173/
          wait-on-timeout: 120
          spec: cypress/e2e/celina2/**
        env:
          VITE_API_URL: http://localhost:8083

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-celina2
          path: cypress/screenshots
